<a href="https://colab.research.google.com/github/nidjaj/Deep-learning/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow

In [15]:
!pip3 list | grep -i tensorflow

mesh-tensorflow          0.0.5                
tensorflow               1.14.0               
tensorflow-estimator     1.14.0               
tensorflow-hub           0.4.0                
tensorflow-metadata      0.13.0               
tensorflow-probability   0.7.0                


In [0]:
import tensorflow as tf

In [0]:
# to assign fixed value in tensorflow we need to define constant
x=tf.constant([30])


In [0]:
# more than one value
# multi value constant
x1=tf.constant([3,5,66,88])

In [19]:
 type(x)

tensorflow.python.framework.ops.Tensor

In [20]:
type(x1)

tensorflow.python.framework.ops.Tensor

In [0]:
 y=tf.constant(20) 

In [0]:
# equation 
z=x+y # new tensor --- Z equation compile and store and wait for resource
# cpu ,GPU ,TPU --


In [23]:
z

<tf.Tensor 'add_1:0' shape=(1,) dtype=int32>

In [24]:
type(z)

tensorflow.python.framework.ops.Tensor

In [0]:
# we have another method to add the same
z1=tf.add(x,y)


In [26]:
z1

<tf.Tensor 'Add_2:0' shape=(1,) dtype=int32>

In [0]:
# now time for assigning  recources to our equation
sess=tf.Session() # connect CPU,GPU TPU


In [0]:
# now we can run our equation
output=sess.run(z)

In [29]:
output

array([50], dtype=int32)

In [0]:
# closing session 
sess.close()















In [0]:
# we can  perform same task in another way where we don't have to close session
with tf.Session() as sess:
  output1=sess.run(z)
  

In [36]:
output1

array([50], dtype=int32)

# placeholder

In [0]:
# first place holder
p1=tf.placeholder(tf.int32)

In [0]:
# placeholder 2
p2=tf.placeholder(tf.int32)

In [0]:
# adding value
sum=tf.add(p1,p2)

In [0]:
# general 
sum1=p1+p2

In [0]:
# time for creating session
with tf.Session() as sess:
  output2=sess.run(sum1,{p1:[3,6],p2:[5,8]})

In [49]:
output2

array([ 8, 14], dtype=int32)